### PR TITLE
Fix restify code in README.

### PR DESCRIPTION
**Pull request by salehhamadeh**

### CODE REVIEW

**Comment by DylanPiercey** [comment]
@salehhamadeh I am not actively testing things with restify but if everything working correctly with that setup? If you can verify this then I will merge this PR.

Thanks!

**Comment by salehhamadeh** [comment]
@DylanPiercey The SSL certificate worked perfectly with debug set to false. I am not sure how it is supposed to work with debug set to true. When I tried that, Chrome gave a warning and showed a red lock instead of a green one.

**Comment by DylanPiercey** [comment]
When debug is true I use the letsencrypt staging server which doesn't create a trusted certificate (hense the error in chrome).

**Comment by salehhamadeh** [comment]
Ok then I guess it is working right.

**Comment by DylanPiercey** [comment]
Thanks for the PR.

**Pull request merged**
