### PR TITLE
fallback to USERPROFILE environment variable if HOME doesn't exist

### PR DESCRIPTION
**Pull request by kufii**
HOME isn't set by default on Windows, USERPROFILE is

### CODE REVIEW

**Comment by DylanPiercey** [comment]
@kufii thanks for the PR. My understanding was that there was a few issues preventing this working on windows (https://github.com/DylanPiercey/auto-sni/issues/7). I will merge this PR but can you confirm this is accurate?

**Comment by kufii** [comment]
certainly possible considering I haven't gotten it to work yet, but I'm not sure yet if my problem is on your end or with my openssl installation. Gonna test more

**Comment by kufii** [comment]
just did another commit that fixes the subject doesn't start with '/' error

Still doesn't fully work for me though, now I'm getting the following error message, I'll do some more investigating when I get a chance:

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:287:9)
    at Function.Buffer.from (buffer.js:133:10)
    at new Buffer (buffer.js:112:17)
    at b64ToBinstr (...\node_modules\letiny-core\lib\letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (...\node_modules\letiny-core\lib\letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (...\node_modules\letiny-core\lib\letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (...\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at ...\node_modules\letsencrypt\lib\accounts.js:109:21
    at tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (...\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (...\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (...\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (...\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (...\node_modules\bluebird\js\release\promise.js:630:18)
    at PromiseArray._resolve (...\node_modules\bluebird\js\release\promise_array.js:125:19)
AutoSNI LetsEncrypt Error: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:287:9)
    at Function.Buffer.from (buffer.js:133:10)
    at new Buffer (buffer.js:112:17)
    at b64ToBinstr (...\node_modules\letiny-core\lib\letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (...\node_modules\letiny-core\lib\letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (...\node_modules\letiny-core\lib\letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (...\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at ...\node_modules\letsencrypt\lib\accounts.js:109:21
    at tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (...\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (...\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (...\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (...\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (...\node_modules\bluebird\js\release\promise.js:630:18)
    at PromiseArray._resolve (...\node_modules\bluebird\js\release\promise_array.js:125:19)
Will fall back to self signed certificate.
```

**Comment by kufii** [comment]
any idea why github is saying the build failed?

**Comment by kufii** [comment]
the build error doesn't really make any sense here

**Comment by DylanPiercey** [comment]
@kufii are you using node 6? I have not been able to get it to work there, waiting on https://github.com/Daplie/node-letsencrypt/issues/23.

**Comment by kufii** [comment]
ah yeah I am on node 6, and unfortunately some of the other parts of my project depend on node 6. So I guess this issue is fixed then? It is generating the certificate properly

**Comment by DylanPiercey** [comment]
I am closing this since it currently does not add windows support. I would accept a new PR that fully added support granted that a few others also vouched this since I am not officially supporting windows.

Thanks again for your PR, it was good work.

**Pull request closed without merging**
