### PR TITLE
Add section about where certs are stored

### PR DESCRIPTION
**Pull request by rcpeters**

### CODE REVIEW

**Comment by DylanPiercey** [comment]
Wicked thanks for the reminder!

**Comment by DylanPiercey** [comment]
@rcpeters does https://github.com/DylanPiercey/auto-sni/commit/4be5726b40fe2f8f89df306785ebeb0f259024e2 look good?

**Comment by rcpeters** [comment]
Indeed!

**Comment by DylanPiercey** [comment]
Sweet, thanks again for your contribution.

**Comment by Mithgol** [comment]
@DylanPiercey

I've noticed that the section “Location of certificates” (introduced by this pull request) is gone after df48500ce18abf1375c4e390cba9d2a4d5eea550.

Where are the certificates from now on?

**Comment by DylanPiercey** [comment]
@Mithgol, looks like I accidentally deleted that. Currently by default it's still in ~/letsencrypt however you can override this with the new 'dir' option.

**Comment by Mithgol** [comment]
Good.

**Pull request merged**
